### ISSUE TITLE
Does not work with Leaflet 1.9.0 or 1.9.1

### ISSUE THREAD

**Issue by saturdaywalkers** [OrdnanceSurvey/leaflet-control-geocoder#1]
Hi

```
Uncaught TypeError: L.hasOwnProperty is not a function
at Control.Geocoder.js:16:14
```

See breaking change in https://github.com/Leaflet/Leaflet/releases/tag/v1.9.0

(it does work with 1.8.0)

Otherwise brilliant!

Cheers,

Andrew

**Comment by aavmurphy** [comment]
just comment out this line near the top to fix it

```
 //L = L && L.hasOwnProperty('default') ? L['default'] : L
```

**Comment by aavmurphy** [comment]
Leafletjs regressed the breaking change in v1.9.2

**Comment by tmnnrs** [comment]
Leaflet [v1.9.2 patch](https://github.com/Leaflet/Leaflet/releases/tag/v1.9.2) has been released which reverts ESM support because of numerous compatibility issues with plugins.
